components:
  schemas:
    CargaOrdemServicoItemVM:
      additionalProperties: false
      properties:
        id:
          format: int32
          type: integer
        tipoOrdemServico:
          nullable: true
          type: string
        codigoProduto:
          nullable: true
          type: string
        descricao:
          nullable: true
          type: string
        numeroNota:
          format: int32
          type: integer
        quantidade:
          format: double
          type: number
        serieNota:
          nullable: true
          type: string
        valorCustoMedio:
          format: double
          type: number
        valorDesconto:
          format: double
          type: number
        valorImpostos:
          format: double
          type: number
        valorTotalBruto:
          format: double
          type: number
        valorTotalLiquido:
          format: double
          type: number
        valorUnitario:
          format: double
          type: number
      title: Produto - Repair
      type: object
    CargaOrdemServicoMecanicoVM:
      additionalProperties: false
      properties:
        cargoTecnico:
          nullable: true
          type: string
        cpfCnpjTecnico:
          nullable: true
          type: string
        nomeTecnico:
          nullable: true
          type: string
        tempoTrabalhado:
          example: 00:00:00
          nullable: true
          type: string
      title: Técnico - Repair
      type: object
    CargaOrdemServicoNotaFiscalVM:
      additionalProperties: false
      properties:
        dataCancelamento:
          format: date-time
          nullable: true
          type: string
        dataFaturamento:
          format: date-time
          nullable: true
          type: string
        numeroNF:
          format: int32
          type: integer
        serie:
          nullable: true
          type: string
        statusNF:
          $ref: '#/components/schemas/StatusNota'
        tipoNF:
          $ref: '#/components/schemas/TipoNota'
        totalNF:
          format: double
          type: number
      type: object
    CargaOrdemServicoPessoaVM:
      additionalProperties: false
      properties:
        cpfCnpj:
          nullable: true
          type: string
        FirstName:
          nullable: true
          type: string
        LastName:
          nullable: true
          type: string
        Email:
          nullable: true
          type: string
        MobNumber:
          nullable: true
          type: string
        TelNumber:
          nullable: true
          type: string
        State:
          nullable: true
          type: string
        City:
          nullable: true
          type: string  
        Country:
          nullable: true
          type: string
        HouseNo:
          nullable: true
          type: string
        Street:
          nullable: true
          type: string
        PostalCode:
          nullable: true
          type: string           
      title: Cliente - Repair Order
      type: object
    CargaOrdemServicoServicoVM:
      additionalProperties: false
      properties:
        id:
          format: int32
          type: integer
        tipoOrdemServico:
          nullable: true
          type: string
        codigoServico:
          nullable: true
          type: string
        descricao:
          nullable: true
          type: string
        funcionarioExecutantes:
          items:
            $ref: '#/components/schemas/CargaOrdemServicoMecanicoVM'
          nullable: true
          type: array
        numeroNota:
          format: int32
          type: integer
        produtos:
          items:
            $ref: '#/components/schemas/CargaOrdemServicoItemVM'
          nullable: true
          type: array
        serieNota:
          nullable: true
          type: string
        TempoMO:
          format: double
          type: number
        valorDesconto:
          format: double
          type: number  
        valorMO:
          format: double
          type: number
      title: Serviço - Repair
      type: object
    CargaOrdemServicoVM:
      additionalProperties: false
      properties:
        id:
          nullable: true
          type: string  
        cliente:
          $ref: '#/components/schemas/CargaOrdemServicoPessoaVM'
        OsNumber:
          nullable: true
          type: string  
        DealerCode:
          nullable: true
          type: string
        codigoControlePrisma:
          nullable: true
          type: string
        dataAbertura:
          format: date-time
          type: string
        dataCancelamento:
          format: date-time
          nullable: true
          type: string
        dataFechamento:
          format: date-time
          nullable: true
          type: string
        descricaoOrdemServico:
          nullable: true
          type: string
        funcionarioAbertura:
          $ref: '#/components/schemas/CargaOrdemServicoVendedorVM'
        funcionarioCancelamento:
          $ref: '#/components/schemas/CargaOrdemServicoVendedorVM'
        motivoCancelamento:
          nullable: true
          type: string
        notasFiscais:
          items:
            $ref: '#/components/schemas/CargaOrdemServicoNotaFiscalVM'
          nullable: true
          type: array
        servicos:
          items:
            $ref: '#/components/schemas/CargaOrdemServicoServicoVM'
          nullable: true
          type: array
        statusOrdemServico:
          $ref: '#/components/schemas/StatusOrdemServico'
        valorDesconto:
          format: double
          type: number
        valorImpostos:
          format: double
          type: number
        valorTotalBruto:
          format: double
          type: number
        valorTotalLiquido:
          format: double
          type: number
        veiculo:
          $ref: '#/components/schemas/CargaOrdemServicoVeiculoVM'
        DMS:
          nullable: true
          type: string
        VersionDMS:
          nullable: true
          type: string  
      title: Repair
      type: object
    CargaOrdemServicoVeiculoVM:
      additionalProperties: false
      properties:
        anoFabricacao:
          format: int32
          type: integer
        anoModelo:
          format: int32
          type: integer
        chassi:
          nullable: true
          type: string
        descricao:
          nullable: true
          type: string
        marca:
          nullable: true
          type: string
        modelo:
          nullable: true
          type: string
        placa:
          nullable: true
          type: string
      title: Veículo - Repair
      type: object
    CargaOrdemServicoVendedorVM:
      additionalProperties: false
      properties:
        cargo:
          nullable: true
          type: string
        cpfCnpj:
          nullable: true
          type: string
        nome:
          nullable: true
          type: string
      title: Funcionario - Repair
      type: object
    CargaVeiculoVM:
      additionalProperties: false
      properties:
        anoFabricacao:
          format: int32
          type: integer
        anoModelo:
          format: int32
          type: integer
        chassi:
          nullable: true
          type: string
        codigoExterno:
          nullable: true
          type: string
        descricao:
          nullable: true
          type: string
        marca:
          nullable: true
          type: string
        modelo:
          nullable: true
          type: string
        placa:
          nullable: true
          type: string
      title: Veículo
      type: object
    CargaVendaVeiculoClienteVM:
      additionalProperties: false
      properties:
        cpfCnpj:
          nullable: true
          type: string
        nome:
          nullable: true
          type: string
        segmento:
          nullable: true
          type: string
        tipoPessoa:
          format: int32
          nullable: true
          type: integer
      title: Cliente - Veículo
      type: object
    CargaVendaVeiculoVM:
      additionalProperties: false
      properties:
        cliente:
          $ref: '#/components/schemas/CargaVendaVeiculoClienteVM'
        concessionariaId:
          format: int32
          type: integer
        dataEntradaVeiculo:
          format: date-time
          type: string
        dataSaidaVeiculo:
          format: date-time
          nullable: true
          type: string
        filialEntradaVeiculoId:
          format: int32
          type: integer
        filialSaidaVeiculoId:
          format: int32
          nullable: true
          type: integer
        id:
          nullable: true
          type: string
        numeroNotaFiscal:
          nullable: true
          type: string
        tipoVendaVeiculo:
          $ref: '#/components/schemas/TipoVenda'
        valorDespesaVeiculo:
          format: double
          nullable: true
          type: number
        valorMargemVeiculo:
          format: double
          nullable: true
          type: number
        valorVendaVeiculo:
          format: double
          nullable: true
          type: number
        veiculo:
          $ref: '#/components/schemas/CargaVeiculoVM'
        vendedor:
          $ref: '#/components/schemas/CargaVendaVeiculoVendedorVM'
      title: Venda de veículo
      type: object
    CargaVendaVeiculoVendedorVM:
      additionalProperties: false
      properties:
        cargo:
          nullable: true
          type: string
        cpfCnpj:
          nullable: true
          type: string
        nome:
          nullable: true
          type: string
        tipoPessoa:
          format: int32
          nullable: true
          type: integer
      title: Vendedor - Veículo
      type: object
    ProblemDetails:
      additionalProperties: {}
      properties:
        detail:
          nullable: true
          type: string
        instance:
          nullable: true
          type: string
        status:
          format: int32
          nullable: true
          type: integer
        title:
          nullable: true
          type: string
        type:
          nullable: true
          type: string
      type: object
    ResultImportPosVendaDto:
      additionalProperties: false
      properties:
        index:
          nullable: true
          type: string
        message:
          nullable: true
          type: string
        status:
          nullable: true
          type: string
      title: ResultadoCarga
      type: object
    StatusNota:
      enum:
      - N (Normal)
      - D (Denegada)
      - C (Cancelada)
      type: string
    StatusOrdemServico:
      enum:
      - A (Aberta)
      - F (Fechada)
      - C (Cancelada)
      - E (Em Andamento)
      type: string
    TipoNota:
      enum:
      - P (Produto)
      - S (Serviço)
      - C (Complementar)
      type: string
    TipoVenda:
      enum:
      - VN
      - VU
      - VD
      - VO
      type: string
  securitySchemes:
    Bearer:
      bearerFormat: JWT
      description: JWT Bearer token
      scheme: bearer
      type: http
info:
  title: Importação Repair Order
  version: V1
openapi: 3.0.1
paths:
  /api/Carga/RepairOrder:
    get:
      requestBody:
        content:
          application/*+json:
            schema:
              items:
                $ref: '#/components/schemas/CargaOrdemServicoVM'
              type: array
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/CargaOrdemServicoVM'
              type: array
          text/json:
            schema:
              items:
                $ref: '#/components/schemas/CargaOrdemServicoVM'
              type: array
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ResultImportPosVendaDto'
                type: array
            text/json:
              schema:
                items:
                  $ref: '#/components/schemas/ResultImportPosVendaDto'
                type: array
            text/plain:
              schema:
                items:
                  $ref: '#/components/schemas/ResultImportPosVendaDto'
                type: array
          description: Success
        '400':
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
            text/json:
              schema:
                items:
                  type: string
                type: array
            text/plain:
              schema:
                items:
                  type: string
                type: array
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
      tags:
      - Carga - Repair Order
  /api/Carga/Veiculo:
    get:
      requestBody:
        content:
          application/*+json:
            schema:
              items:
                $ref: '#/components/schemas/CargaVendaVeiculoVM'
              type: array
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/CargaVendaVeiculoVM'
              type: array
          text/json:
            schema:
              items:
                $ref: '#/components/schemas/CargaVendaVeiculoVM'
              type: array
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ResultImportPosVendaDto'
                type: array
            text/json:
              schema:
                items:
                  $ref: '#/components/schemas/ResultImportPosVendaDto'
                type: array
            text/plain:
              schema:
                items:
                  $ref: '#/components/schemas/ResultImportPosVendaDto'
                type: array
          description: Success
        '400':
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
            text/json:
              schema:
                items:
                  type: string
                type: array
            text/plain:
              schema:
                items:
                  type: string
                type: array
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
      tags:
      - Carga - Veículo
security:
- Bearer: []
